ALLOWED_TABLES = {
    # --- Activas ---
    "Albaran",
    "Categoria",
    "Confeccion",
    "Envase",
    "Finca",
    "Productos",
    "Socio",
    "tblUsuario",
    "TrazaCaja",
    "Vale",
    "Variedad",
    "CajasPalet",
    "RelOCPalet",

    # --- Pendientes de activar ---
    # "Auxiliar",
    # "cabAlbHorto",
    # "cabCortes",
    # "CabeceraPalet",
    # "cabPaletHorto",
    # "CabVisitas",
    # "CalibreHorto",
    # "CategoriaHorto",
    # "CategoriaPlatano",
    # "CatProducto",
    # "CodigoEntrada",
    # "Conductor",
    # "ConfeccionHorto",
    # "ConfEtiquetado",
    # "Empaquetado",
    # "Enfermedades",
    # "EstadoFitosanitario",
    # "Fincados",
    # "Fruta",
    # "GrupoQuimico",
    # "HorProd",
    # "infcatprinc",
    # "LinAlbRec",
    # "lineaAlbHorto",
    # "LineaAlbaran",
    # "LineaCorte",
    # "lineaMatActiva",
    # "LineaValeRec",
    # "malisocio",
    # "materiasActivas",
    # "OrdenCarga",
    # "OrdenSalida",
    # "Otros",
    # "Plagas",
    # "PlazoSeg",
    # "ProductoHorto",
    # "RechazoCajas",
    # "relCajaAguacate",
    # "relCajaPlastico",
    # "rsValeCopia",
    # "tblCambio",
    # "tblEstadoCambio",
    # "tblEtiManual",
    # "tbletiquetado",
    # "tblTrazaPrograma",
    # "tblUsuario",
    # "tecnicos",
    # "TipoEstadoFitosanitario",
    # "tipoProdHorto",
    # "Toxicologia",
    # "trazaCajaHorto",
    # "ValesRec",
    # "VariedadHorto",
    # "Visitas",
}